# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-08-26" # 纪念日
CITY: "烟台"

BIRTHDAY:
  - "01-01"

APP_ID: "wx20ead85e9d6bfcfe"
APP_SECRET: "83c87efc59924d30ef027a2dde5f4312"

USER_ID: 
  - "o4yHL6ee5hU47lSUJGN3eVWEaWu4"
  - "USER ID 2"o4yHL6ZPmnZ9tE6se27DvDfvJzuo"
TEMPLATE_ID: "cPETf_Ja8pFoIv8kh2TbBEDMEfLNgHDlSuaz_Fpkwh0"
